//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OreToManufacturing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OreToManufacturing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12180,1218,Arkonor Processing
        ///12181,1218,Bistot Processing
        ///12182,1218,Crokite Processing
        ///12183,1218,Dark Ochre Processing
        ///12184,1218,Gneiss Processing
        ///12185,1218,Hedbergite Processing
        ///12186,1218,Hemorphite Processing
        ///12187,1218,Jaspet Processing
        ///12188,1218,Kernite Processing
        ///12189,1218,Mercoxit Processing
        ///12190,1218,Omber Processing
        ///12191,1218,Plagioclase Processing
        ///12192,1218,Pyroxeres Processing
        ///12193,1218,Scordite Processing
        ///12194,1218,Spodumain Processing
        ///12195,1218,Veldspar Processing.
        /// </summary>
        internal static string reprocessing_skills {
            get {
                return ResourceManager.GetString("reprocessing_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,#System
        ///2,2,Corporation
        ///3,3,Region
        ///4,4,Constellation
        ///5,5,Solar System
        ///6,6,Sun G5 (Yellow)
        ///7,6,Sun K7 (Orange)
        ///8,6,Sun K5 (Red Giant)
        ///9,6,Sun B0 (Blue)
        ///10,6,Sun F0 (White)
        ///11,7,Planet (Temperate)
        ///12,7,Planet (Ice)
        ///13,7,Planet (Gas)
        ///14,8,Moon
        ///15,9,Asteroid Belt
        ///16,10,Stargate (Caldari System)
        ///17,10,Stargate (Amarr Constellation)
        ///18,458,Plagioclase
        ///19,461,Spodumain
        ///20,457,Kernite
        ///21,454,Hedbergite
        ///22,450,Arkonor
        ///23,12,Cargo Container
        ///24,13,Ring
        ///25,14,Corpse
        ///26,16,Office Folder
        ///27, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tiamat_typeids {
            get {
                return ResourceManager.GetString("tiamat_typeids", resourceCulture);
            }
        }
    }
}
